/**
 * SketchFlow — wireframe-to-code converter
 *
 * Generates production-ready HTML/CSS from structured wireframe descriptions.
 * Inspired by design-to-code AI trends.
 *
 * @packageDocumentation
 */

export { SketchFlow } from "./core";
export type {
  ComponentType,
  ComponentProps,
  SketchComponent,
  WireframeSpec,
} from "./core";
export { loadConfig, defaultConfig } from "./config";
export type { SketchFlowConfig } from "./config";
export {
  escapeHtml,
  wrapTag,
  buildAttributes,
  selfClosingTag,
  cssRule,
  mediaQuery,
  indent,
  hexToRgb,
  rgbToHex,
  lightenColor,
  darkenColor,
  toClassName,
} from "./utils";

// ─── CLI Quick-Run ───────────────────────────────────────────────────────────

if (require.main === module) {
  const { SketchFlow } = require("./core");
  const sf = new SketchFlow();

  const demoSpec = {
    title: "SketchFlow Demo",
    description: "A sample page generated by SketchFlow",
    components: [
      { id: "h1", type: "header" as const, props: { text: "SketchFlow" } },
      {
        id: "nav1",
        type: "nav" as const,
        props: { links: ["Home", "Features", "Docs", "Contact"] },
      },
      {
        id: "hero1",
        type: "hero" as const,
        props: {
          text: "Design to Code, Instantly",
          subtitle:
            "Describe your wireframe, get production-ready HTML & CSS.",
        },
      },
      {
        id: "grid1",
        type: "grid" as const,
        props: {
          columns: 3,
          children: [
            { id: "c1", type: "card" as const, props: { text: "Fast", subtitle: "Generate pages in milliseconds." } },
            { id: "c2", type: "card" as const, props: { text: "Flexible", subtitle: "8 built-in component types." } },
            { id: "c3", type: "card" as const, props: { text: "Themeable", subtitle: "Full color & font control." } },
          ],
        },
      },
      {
        id: "f1",
        type: "footer" as const,
        props: { text: "\u00A9 2026 SketchFlow by Officethree Technologies" },
      },
    ],
  };

  const page = sf.generatePage(demoSpec);
  console.log(page);
}
